### PR TITLE
Added support to build project with CMake

### PR DESCRIPTION
**Pull request by devsdmf**
Hi there,

I took some time to do a simple cmake build system implementation from my point of view that would be good for the project.

Also, I took the freedom to make some decisions for the project structure as the current build system (Bazel) provides an easier way to deal with the project dependencies. So, what I did was to add the dependent project (abseil-cpp) as a submodule of the project, if you guys think that would be better to set this dependency directly into the _libs_ folder instead of using a git submodule, I can do the changes. Or if you get any better idea of how to deal with it, pls, let me know so I can make the changes.

### CODE REVIEW

**Comment by devsdmf** [comment]
I signed it!

**Comment by devsdmf** [comment]
Hi there, any news about this?

**Comment by sdolgikh** [comment]
@devsdmf  Hi. As I can see, your CMake configuration is incomplete. You don't provide targets for library and tests (no calls for add_library/add_tests). Which is curious, because this project is intended to be used as library at first.

**Comment by lvandeve** [comment]
Hi, would you mind changing the url of hte submodule from git@github.com:abseil/abseil-cpp.git into https://github.com/abseil/abseil-cpp.git

because then building should work for everyone, while the git@ url requires ssh access afaik

**Comment by devsdmf** [comment]
Awesome, I'll do the changes tonight, thanks for the feedbacks! (:

**Comment by devsdmf** [comment]
@sdolgikh you said "this project is intended to be used as library at first", so I have a question, should the target be named something like `librobots` ?

**Comment by devsdmf** [comment]
Done.

**Comment by devsdmf** [comment]
Done, added static and shared libraries and tests

**Comment by devsdmf** [comment]
Now, I have a question regarding to the project dependencies.

Do you prefer to download the dependencies using CMake ExternalProject's feature instead of using it as git submodules?

**Comment by devsdmf** [comment]
Also, I changed the dependency management approach to use _configure time_ based resolution instead of git submodules.

**Comment by lvandeve** [comment]
As of commit 5a7d82f35d20acdb2ae28861fb69448749b82da5, when following the instructions, using "make" after "cmake .. -DENABLE_TESTS=1" there's a linker error:

/usr/bin/ld: c-build/libs/abseil-cpp-src/absl/strings/libabsl_absl_strings.a(ascii.cc.o): relocation R_X86_64_PC32 against symbol `_ZN4absl14ascii_internal8kToLowerE' can not be used when making a shared object; recompile with -fPIC

Can you reproduce it as well?

**Comment by devsdmf** [comment]
Weird, I didn't got this error. What's your environment? (OS, compiler, etc..)

**Comment by lvandeve** [comment]
Trying on Linux with gcc version 9.1.0, ld version (GNU Binutils) 2.32, clang v 8.0.0, cmake version 3.14.5
It's something related to the shared libary of course, not sure what exactly

**Comment by devsdmf** [comment]
Ok, I'm working from my macbook, I'll try in my linux computer tonight at home.

**Comment by lvandeve** [comment]
Maybe it's a matter of adding the -fPIC flag somewhere (I couldn't currently tell where exactly though)

**Comment by devsdmf** [comment]
@sdolgikh thanks for the tip, I've made the changes in the `CMakeLists.txt` to set the correct flag. 

Regarding to the `make test` target, I've tested adding the `--verbose` flag to the `ctest` command, and it works as expected.

I'm looking now for the problem with the build in a sibling folder, I'll push the changes in a few minutes.

**Comment by devsdmf** [comment]
@sdolgikh I've tested the out of sources build and I could not reproduce the error, I don't know if the changes that I've pushed already fixed the problem, can you re-run your testes and let me know the error stills happening?

**Comment by sdolgikh** [comment]
@devsdmf I guess you neet to set CMAKE_POSITION_INDEPENDENT_CODE earlier, because it still fails with the same error. I placed it in the "build options" section.

Use this container to reproduce the problem:

```Dockerfile
FROM ubuntu:18.04
RUN apt update && apt upgrade -y
RUN apt install -y build-essential cmake git-core
RUN useradd -M -u 1001 -r cmakebuild && chown -R cmakebuild: /usr/src
USER cmakebuild
WORKDIR /usr/src
RUN git clone --depth=1 -b cmake-build https://github.com/devsdmf/robotstxt.git
RUN mkdir /usr/src/robotstxt-build
WORKDIR /usr/src/robotstxt-build
RUN /usr/bin/cmake /usr/src/robotstxt -DROBOTS_BUILD_TESTS=ON
ENV VERBOSE=1
RUN make
RUN make test
```

The problem with out-of-source builds seems to be solved in the latest revision.

**Comment by devsdmf** [comment]
Awesome! Now the issue is fixed! Ty!

**Comment by lvandeve** [comment]
It works for me too, thanks!

**Pull request merged**
